server:
  port: 8082

spring:
  application:
    name: auth

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties.hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
      default_batch_fetch_size: 1000
      globally_quoted_identifiers: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000         # 1시간 (ms)
  refresh-token-expiration: 604800000      # 7일 (ms)
